# Generated by Django 5.0 on 2024-01-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('engine_fuel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_hp', models.IntegerField(blank=True, null=True)),
                ('engine_cylinders', models.IntegerField(blank=True, null=True)),
                ('transmission_type', models.CharField(max_length=255)),
                ('driven_wheels', models.CharField(max_length=255)),
                ('number_of_doors', models.IntegerField(blank=True, null=True)),
                ('market_category', models.CharField(max_length=255)),
                ('vehicle_size', models.CharField(max_length=255)),
                ('vehicle_style', models.CharField(max_length=255)),
                ('highway_mpg', models.IntegerField()),
                ('city_mpg', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('msrp', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
